name: Testing
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download arcctl
        run: curl -sSL https://arcctl-backend.nyc3.digitaloceanspaces.com/arcctl --output arcctl
      - name: Make arcctl executable
        run: chmod +x ./arcctl
      - name: Setup arcctl
        run: ./arcctl set secretAccount --provider s3 --creds accessKeyId=${{secrets.ACCESS_KEY_ID}} --cred secretAccessKey=${{secrets.SECRET_ACCESS_KEY}} --creds endpoint=https://nyc3.digitaloceanspaces.com --creds region=nyc3
      - name: Test
        run: ./arcctl list account
